# Data Preprocessing Tools

## Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [5]:
df = pd.read_csv('Data.csv')
df.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [13]:
X = df.iloc[:, :-1].values  #We are creating a numpy array, not a data frame
X #Matrix of Features

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [12]:
Y = df.iloc[:, -1].values
Y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

## Taking care of missing data

In [18]:
from sklearn.impute import SimpleImputer #to take care of missing values (replace by avg etc.)

si = SimpleImputer(missing_values=np.nan, strategy = 'mean')

si.fit(X[:, 1:3]) #Only numerical Values[AGE AND SALARY]
X[:, 1:3] = si.transform(X[:, 1:3])
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

## Encoding categorical data

### Encoding the Independent Variable

#### CLASS COL to NEW COLS (one hot encoding)

In [25]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])] ,remainder='passthrough')
X = ct.fit_transform(X)
X = np.array(X)

In [26]:
print(X)

[[0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

Y = le.fit_transform(Y)### Encoding the Dependent Variable

In [28]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.3, random_state = 1) #as set will be randomly generated (for same split)

In [31]:
print(X_train)

[[1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 0.0 35.0 58000.0]]


In [32]:
print(X_test)

[[1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 37.0 67000.0]
 [1.0 0.0 0.0 1.0 38.77777777777778 52000.0]]


In [33]:
print(Y_train)

[1 0 0 1 1 0 1]


In [34]:
print(Y_test)

[0 1 0]


## Feature Scaling

In [38]:
#to make sure some features do not dominate the model. [Not required in every model]
#two methods.
#1. (value- mean(all_values))/stddev(all_values) STANDARDISATION [always work, generally]
#2. (value-min(all_values))/(max(all_values)-min(all_values)) NORMALISATION when normal distribution

#{makes values b/ 0 and 1}

#[not to apply to dummy variable]

In [44]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

X_train[:, 3:] = sc.fit_transform(X_train[:, 3:])
X_test[:, 3:] = sc.transform(X_test[:, 3:])


In [45]:
print(X_train)

[[1.0 0.0 1.0 -0.6324555320336758 -0.038910211282047996
  -0.22960023388015188]
 [0.0 1.0 0.0 -0.6324555320336758 0.5058327466666259 0.49120534884662787]
 [1.0 0.0 0.0 1.5811388300841895 -0.3112816902563849 -0.4731156334500103]
 [1.0 0.0 0.0 1.5811388300841895 -1.809324824615238 -1.6127677034369463]
 [0.0 1.0 0.0 -0.6324555320336758 1.0505757046152997 1.1048641557626704]
 [1.0 0.0 1.0 -0.6324555320336758 1.3229471835896367 1.455526331143266]
 [0.0 1.0 0.0 -0.6324555320336758 -0.7198389087178904 -0.736112264985457]]


In [46]:
print(X_test)

[[1.0 0.0 1.0 -0.6324555320336758 -1.4007676061537326 -1.0867744403660526]
 [0.0 1.0 0.0 -0.6324555320336758 -0.4474674297435534 0.05287762962088326]
 [1.0 0.0 0.0 1.5811388300841895 -0.20535944843303158 -1.2621055280563505]]
